'use client';
import { useState } from 'react';
const fmt=(ms:number)=>{if(!ms)return '-';const s=Math.floor(ms/1000);return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
export default function Admin(){
 const [pass,setPass]=useState(''); const [ok,setOk]=useState(false); const [rows,setRows]=useState<any[]>([]); const [msg,setMsg]=useState('');
 async function load(){const r=await fetch('/api/admin/results',{headers:{'x-admin-password':pass}});const j=await r.json(); if(!r.ok){setMsg(j.error);return} setRows(j.results||[]);setOk(true)}
 async function exportX(){const r=await fetch('/api/admin/export',{headers:{'x-admin-password':pass}}); const blob=await r.blob(); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='wyniki_quizu_rg.xlsx'; a.click()}
 async function notify(){if(!confirm('Wysłać maile do TOP 3?'))return; const r=await fetch('/api/admin/notify',{method:'POST',headers:{'x-admin-password':pass}}); const j=await r.json(); setMsg(r.ok?`Wysłano: ${j.sent}`:j.error)}
 if(!ok)return <main className="admin"><div className="adminLogin"><h1>Panel admina</h1><p className="small">Test wiedzy o Recepcie Gemini</p><input className="input" type="password" placeholder="Hasło admina" value={pass} onChange={e=>setPass(e.target.value)}/><br/><br/><button className="btn" onClick={load}>Zaloguj</button>{msg&&<div className="error">{msg}</div>}</div></main>
 const completed=rows.filter(r=>r.completed).length; const perfect=rows.filter(r=>r.score===4).length; const avg=completed?Math.round(rows.reduce((a,r)=>a+(r.duration_ms||0),0)/completed):0;
 return <main className="admin"><div className="adminBox"><div className="adminHead"><div><div className="brand"><span className="logo">✣</span>Recepta Gemini</div><h1>Wyniki konkursu</h1><p className="small">Test wiedzy o Recepcie Gemini</p></div><div className="actions"><button className="btn secondary" onClick={load}>Odśwież</button><button className="btn" onClick={exportX}>Eksport do Excel</button><button className="btn" onClick={notify}>Wyślij maile TOP 3</button></div></div>{msg&&<div className="error">{msg}</div>}<div className="grid"><div className="stat">Uczestnicy<br/><b>{rows.length}</b></div><div className="stat">Ukończone<br/><b>{completed}</b></div><div className="stat">Komplet 4/4<br/><b>{perfect}</b></div><div className="stat">Średni czas<br/><b>{fmt(avg)}</b></div></div><div className="tableWrap"><h2>Ranking</h2><table><thead><tr><th>#</th><th>Imię</th><th>Nazwisko</th><th>Email</th><th>Wynik</th><th>Czas</th><th>Zakończono</th><th>Mail</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id}><td>{i+1}</td><td>{r.first_name}</td><td>{r.last_name}</td><td>{r.email}</td><td>{r.score}/4</td><td>{fmt(r.duration_ms)}</td><td>{r.finished_at?new Date(r.finished_at).toLocaleString('pl-PL'):'-'}</td><td>{r.notified?'TAK':'NIE'}</td></tr>)}</tbody></table></div></div></main>
}
